publish_mode: editorial_workflow
media_folder: "www/assets/img"
public_folder: "/img"
backend:
  name: git-gateway
  branch: master
collections:
  - name: ships
    label: Ships
    folder: www/ships
    identifierField: slug
    create: true
    slug: "{{slug}}-{{imo}}"
    fields:
      - {name: "layout", label: "Layout", widget: "hidden", default: "company"}
      - {name: "tags", label: "Tags", widget: "hidden", default: ["ship"]}
      - {name: "name", label: "Name", widget: "string"}
      - {name: "imo", label: "IMO", widget: "string"}
      - {name: "slug", label: "Slug", widget: "string"}
      - name: "company"
        label: "Company"
        widget: "relation"
        collection: "companies"
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["{{name}} ({{country}})"]
      - {name: "capacityPax", label: "Capacity (persons)", widget: "number"}
      - {name: "wikipediaUrl", label: "Wikipedia URL", widget: "string"}
      - {name: "photo", label: "Photo", widget: "image"}
      - label: Routes
        name: routes
        widget: relation
        collection: routes
        multiple: true
        search_fields: ["slug"]
        value_field: "slug"
        display_fields: ["slug"]
      - {name: "outOfScope", label: "Out of scope (not a passenger ferry)", widget: "boolean", required: false}
  - name: companies
    label: Companies
    folder: www/companies
    create: true
    identifierField: slug
    slug: "{{slug}}-{{imo}}"
    fields:
      - {name: "layout", label: "Layout", widget: "hidden", default: "company"}
      - {name: "tags", label: "Tags", widget: "hidden", default: ["company"]}
      - {name: "name", label: "Name", widget: "string"}
      - {name: "imo", label: "IMO", widget: "string"}
      - {name: "slug", label: "Slug", widget: "string"}
      - {name: "country", label: "Country Code", widget: "string"}
      - {name: "officialUrl", label: "Website URL", widget: "string"}
      - {name: "wikipediaUrl", label: "Wikipedia URL", widget: "string"}
  - name: routes
    label: Routes
    folder: www/routes
    create: true
    identifierField: slug
    fields:
      - {name: "layout", label: "Layout", widget: "hidden", default: "route"}
      - {name: "tags", label: "Tags", widget: "hidden", default: ["route"]}
      - {name: "slug", label: "Slug", widget: "string"}
      - {name: "cityA", label: "City A", widget: "string"}
      - {name: "cityB", label: "City B", widget: "string"}
  - name: cities
    label: Cities
    folder: www/cities
    create: true
    identifierField: slug
    fields:
      - {name: "layout", label: "Layout", widget: "hidden", default: "city"}
      - {name: "tags", label: "Tags", widget: "hidden", default: ["city"]}
      - {name: "name", label: "Name", widget: "string"}
      - {name: "country", label: "Country", widget: "string"}
      - {name: "slug", label: "Slug", widget: "string"}
      - {name: "geonamesId", label: "GeoNames ID", widget: "string"}
      - {name: "latitude", label: "Latitude", widget: "number"}
      - {name: "longitude", label: "Longitude", widget: "number"}
