publish_mode: editorial_workflow
media_folder: www/img
public_folder: /img
site_url: https://www.greenferries.org
display_url: https://www.greenferries.org
logo_url: https://www.greenferries.org/img/logo-greenferries.png
backend:
  name: git-gateway
  branch: master
  squash_merges: true
collections:
  - name: ships
    label: Ships
    label_singular: Ship
    folder: www/11ty_input/ships
    identifierField: slug
    create: true
    slug: "{{fields.slug}}"
    summary: "{{name}} - {{company}} - {{routes}}"
    view_filters:
      - label: In scope
        field: outOfScope
        pattern: false|null
      - label: Out of scope
        field: outOfScope
        pattern: true
    fields:
      - {name: "layout", label: "Layout", widget: "hidden", default: "company"}
      - {name: "tags", label: "Tags", widget: "hidden", default: ["ship"]}
      - {name: "name", label: "Name", widget: "string"}
      - {name: "imo", label: "IMO", widget: "string"}
      - {name: "slug", label: "Slug", widget: "string"}
      - name: "company"
        label: "Company"
        widget: "relation"
        collection: "companies"
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["{{name}} ({{country}})"]
      - {name: "capacityPax", label: "Capacity (persons)", widget: "number", required: false}
      - {name: "wikipediaUrl", label: "Wikipedia URL", widget: "string", required: false}
      - {name: "photo", label: "Photo", widget: "image", required: false}
      - label: Routes
        name: routes
        widget: relation
        collection: routes
        multiple: true
        search_fields: ["slug"]
        value_field: "slug"
        display_fields: ["slug"]
        required: false
      - {name: "outOfScope", label: "Out of scope (not a passenger ferry)", widget: "boolean", required: false}
  - name: companies
    label: Companies
    label_singular: Company
    folder: www/11ty_input/companies
    create: true
    identifierField: slug
    slug: "{{slug}}-{{imo}}"
    fields:
      - {name: "layout", label: "Layout", widget: "hidden", default: "company"}
      - {name: "tags", label: "Tags", widget: "hidden", default: ["company"]}
      - {name: "name", label: "Name", widget: "string"}
      - {name: "imo", label: "IMO", widget: "string", required: false}
      - {name: "slug", label: "Slug", widget: "string"}
      - {name: "country", label: "Country Code", widget: "string"}
      - {name: "officialUrl", label: "Website URL", widget: "string"}
      - {name: "wikipediaUrl", label: "Wikipedia URL", widget: "string"}
  - name: routes
    label: Routes
    label_singular: Route
    folder: www/11ty_input/routes
    create: true
    identifierField: slug
    fields:
      - {name: "layout", label: "Layout", widget: "hidden", default: "route"}
      - {name: "tags", label: "Tags", widget: "hidden", default: ["route"]}
      - {name: "slug", label: "Slug", widget: "string"}
      - name: cityA
        label: City A
        widget: relation
        collection: cities
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["name", "country"]
      - name: cityB
        label: City B
        widget: relation
        collection: cities
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["name", "country"]
      - {name: "distanceKm", label: "Distance KM", widget: "number"}
  - name: cities
    label: Cities
    label_singular: City
    folder: www/11ty_input/cities
    create: true
    identifierField: slug
    summary: "{{name}} - {{country}}"
    view_groups:
      - {label: "Country", field: country}
    sortable_fields: ["name"]
    fields:
      - {name: "layout", label: "Layout", widget: "hidden", default: "city"}
      - {name: "tags", label: "Tags", widget: "hidden", default: ["city"]}
      - {name: "name", label: "Name", widget: "string"}
      - {name: "country", label: "Country", widget: "string"}
      - {name: "slug", label: "Slug", widget: "string"}
      - {name: "geonamesId", label: "GeoNames ID", widget: "string"}
      - {name: "latitude", label: "Latitude", widget: "number"}
      - {name: "longitude", label: "Longitude", widget: "number"}
