name: Update new data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r greenferries/requirements.txt
    - name: Run data pipeline
      run: python -m greenferries.full_pipeline
      env:
        WIKIDATA_USERNAME: ${{ secrets.WIKIDATA_USERNAME }}
        WIKIDATA_PASSWORD: ${{ secrets.WIKIDATA_PASSWORD }}
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Update data"
    - name: Push changes
      run: git push origin master
